### PR TITLE
[WIP] Webdriverio integration + refactor

### PR DESCRIPTION
**Pull request by zoepage**

### CODE REVIEW

**Comment by gr2m** [comment]
Could you start a separate PR which only removes bower.json & bower_components and adjust the index.html accordingly? That will let us do code review for the actual work, which is currently not possible because to many files have been changed.

One bug I found is `"webdriverio": "^3.2."` in package.json, the version is invalid

**Comment by zoepage** [comment]
This PR is still a WIP. Thought you might wanna give it a try as we use another webdriver / setup as you suggested.

I fix the dependency. If you want to run the tests, you can run `npm run test:mocha` or `npm run test:wdio`, after starting the `start_selenium_with_chromedriver`. Standard is still throwing errors that *kind of* do not make sense. 

Will clean up the commits when I'm done with the tests.

**Comment by zoepage** [comment]
@gr2m https://github.com/gr2m/smartdate-input/blob/webdriverio/test/smartdate-input.js#L69
Looks like `date` gets ignored... not sure why (timestamp doesn't work either)

**Comment by gr2m** [comment]
closing in favor of https://github.com/gr2m/smartdate-input/pull/8. It's rebased on gh-pages and has only the webdriverio-related changes, for easier review / discussion

**Pull request closed without merging**
